AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'bin/**/*'
    - 'bin/bundle'
    - 'bin/bundle*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config/puma.rb'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'config/importmap.rb'
    - 'config/routes.rb'
    - 'config.ru'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

plugins:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false
